#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail=0

check() {
  local description="$1"
  shift
  if "$@"; then
    echo "PASS: $description"
  else
    echo "FAIL: $description"
    fail=1
  fi
}

check "README exists" test -s "$repo_root/README.md"
check "Core lab values exist" test -s "$repo_root/config/core-lab/core-lab.tfvars.example"
check "Full platform values exist" test -s "$repo_root/config/full-platform/full-platform.tfvars.example"
check "Remote state bootstrap exists" test -s "$repo_root/bootstrap/main.tf"
check "Coverage matrix exists" test -s "$repo_root/docs/09-review/coverage-matrix.md"
check "Microsoft Learn review exists" test -s "$repo_root/docs/09-review/microsoft-learn-review.md"
check "No committed local tfvars" bash -c "! find '$repo_root' -type f \\( -name 'terraform.tfvars' -o -name '*.auto.tfvars' -o -name 'backend.hcl' \\) | grep -q ."
check "No committed state" bash -c "! find '$repo_root' -type f \\( -name '*.tfstate' -o -name '*.tfstate.*' -o -name '*.tfplan' \\) | grep -q ."
check "No obvious secrets" bash -c "! grep -R -n -E '(client_secret|password|access_key)[[:space:]]*=' '$repo_root' --include='*.tf' --include='*.tfvars*'"
check "Twelve editable diagrams exist" bash -c "test \"\$(find '$repo_root/docs/diagrams/source' -name '*.drawio' | wc -l)\" -ge 12"
check "Twelve SVG exports exist" bash -c "test \"\$(find '$repo_root/docs/diagrams/svg' -name '*.svg' | wc -l)\" -ge 12"
check "Twelve PNG exports exist" bash -c "test \"\$(find '$repo_root/docs/diagrams/png' -name '*.png' | wc -l)\" -ge 12"
check "No tool-generation branding" bash -c "! grep -R -n -E '(ChatGPT|Codex|AI-generated|generated by AI|as an AI)' '$repo_root' --exclude='*.png' --exclude='check-repository.sh' --exclude-dir='.git' --exclude-dir='.terraform'"
check "Terraform tests exist" bash -c "test \"\$(find '$repo_root/platform/tests' -name '*.tftest.hcl' | wc -l)\" -ge 2"
check "Local documentation links resolve" bash "$repo_root/scripts/check-links.sh"

exit "$fail"
